name: ammarcafe
description: "That is my cafe isa"


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.5.4







dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.1.2
  provider: ^6.0.0
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.2
  # firebase packges
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.1
  firebase_messaging: ^15.2.1
  firebase_auth: ^5.4.1
  google_sign_in: ^6.2.2
  awesome_dialog: ^3.2.1
  flutter_speed_dial: ^7.0.0
  flutter_image_compress: ^2.4.0
  supabase_flutter: ^2.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^4.0.0





flutter:

  
  
  
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/DD.json
    - assets/icons/socialmedia/
    - assets/icons/logo/logo_white.png


  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
